### ISSUE TITLE
Refactor LambdaInfo.equals() and App.runInteractiveMode()

### ISSUE THREAD

**Issue by alzahraasalman** [DD2480-Project-group-25/java-design-patterns#42]
Refactor App.runInteractiveMode() by writing several  helper  methods  that  runInteractiveMode()  calls. These  helper  methods  could  be  one for each of the options that the user can choose from.
Refactor LambdaInfo.equals() by using Objects’ equals()-method

**Comment by alzahraasalman** [comment]
The complexity of LambdaInfo.equals() is reduced from 15 to 8.
The complexity of App.runInteractiveMode() is reduced from 14 to 6.

**Comment by vronc** [comment]
Fixed by #46
